version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jomjoam12}-
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - ./locales:/app/locales  # Add this line for translations
    ports:
      - "8000:8000"
    environment:
      - DEFAULT_LANG=en
      - SUPPORTED_LANGS=en,sw,fr
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jomjoam12}-
      - POSTGRES_DB=mydatabase
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: